<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Follow up pair-wise comparisons | Final Assignment</title>
  <meta name="description" content="This is an organized index of the 5 practical assignments and the final writing project that PSY309 students at UTM will complete during the Fall 2024 semester." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Follow up pair-wise comparisons | Final Assignment" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an organized index of the 5 practical assignments and the final writing project that PSY309 students at UTM will complete during the Fall 2024 semester." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Follow up pair-wise comparisons | Final Assignment" />
  
  <meta name="twitter:description" content="This is an organized index of the 5 practical assignments and the final writing project that PSY309 students at UTM will complete during the Fall 2024 semester." />
  

<meta name="author" content="JLB" />


<meta name="date" content="2024-09-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="capstone-project-a-simulated-research-paper.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Psy309 Computational Assignments</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="1" data-path="asking-scientific-questions-and-literature-review.html"><a href="asking-scientific-questions-and-literature-review.html"><i class="fa fa-check"></i><b>1</b> Asking Scientific Questions and Literature Review</a>
<ul>
<li class="chapter" data-level="1.1" data-path="asking-scientific-questions-and-literature-review.html"><a href="asking-scientific-questions-and-literature-review.html#overview"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="asking-scientific-questions-and-literature-review.html"><a href="asking-scientific-questions-and-literature-review.html#choose-a-reasearch-topic-in-psychology"><i class="fa fa-check"></i><b>1.2</b> 1. Choose a Reasearch Topic in Psychology</a></li>
<li class="chapter" data-level="1.3" data-path="asking-scientific-questions-and-literature-review.html"><a href="asking-scientific-questions-and-literature-review.html#see-whats-out-there"><i class="fa fa-check"></i><b>1.3</b> 2. See What’s Out There</a></li>
<li class="chapter" data-level="1.4" data-path="asking-scientific-questions-and-literature-review.html"><a href="asking-scientific-questions-and-literature-review.html#reflect"><i class="fa fa-check"></i><b>1.4</b> 3. Reflect</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="exploring-types-of-measurement-in-research.html"><a href="exploring-types-of-measurement-in-research.html"><i class="fa fa-check"></i><b>2</b> Exploring Types of Measurement in Research</a>
<ul>
<li class="chapter" data-level="" data-path="exploring-types-of-measurement-in-research.html"><a href="exploring-types-of-measurement-in-research.html#identify-dependent-variables"><i class="fa fa-check"></i>1. Identify dependent variable(s)</a></li>
<li class="chapter" data-level="" data-path="exploring-types-of-measurement-in-research.html"><a href="exploring-types-of-measurement-in-research.html#identify-claims-made-by-the-paper"><i class="fa fa-check"></i>2. Identify claim(s) made by the paper</a></li>
<li class="chapter" data-level="" data-path="exploring-types-of-measurement-in-research.html"><a href="exploring-types-of-measurement-in-research.html#critically-evaluate-the-measuement-approach"><i class="fa fa-check"></i>3. Critically Evaluate the Measuement Approach</a></li>
<li class="chapter" data-level="" data-path="exploring-types-of-measurement-in-research.html"><a href="exploring-types-of-measurement-in-research.html#develop-a-research-idea"><i class="fa fa-check"></i>4. Develop a Research Idea</a></li>
<li class="chapter" data-level="" data-path="exploring-types-of-measurement-in-research.html"><a href="exploring-types-of-measurement-in-research.html#reflect-1"><i class="fa fa-check"></i>5. Reflect</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html"><i class="fa fa-check"></i><b>3</b> Manipulations and Covariates</a>
<ul>
<li class="chapter" data-level="" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html#connecting-covariates-to-your-topic-of-interest"><i class="fa fa-check"></i>1. Connecting covariates to your topic of interest</a></li>
<li class="chapter" data-level="" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html#experiments-manipulating-independent-variables"><i class="fa fa-check"></i>2. Experiments: Manipulating Independent Variable(s)</a></li>
<li class="chapter" data-level="" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html#connect-the-theory-to-computation-in-r"><i class="fa fa-check"></i>3. Connect the theory to computation in R!</a></li>
<li class="chapter" data-level="" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html#reflect-2"><i class="fa fa-check"></i>4. Reflect</a></li>
<li class="chapter" data-level="" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html#code-for-practical-3"><i class="fa fa-check"></i>Code For Practical #3</a>
<ul>
<li class="chapter" data-level="" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html#object-oriented-programming"><i class="fa fa-check"></i>Object-oriented programming</a></li>
<li class="chapter" data-level="" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html#random-number-generation"><i class="fa fa-check"></i>Random number generation</a></li>
<li class="chapter" data-level="" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html#sample-from-the-normal-distribution"><i class="fa fa-check"></i>Sample from the normal distribution</a></li>
<li class="chapter" data-level="" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html#sampling-from-a-list-of-values"><i class="fa fa-check"></i>Sampling from a list of values</a></li>
<li class="chapter" data-level="" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html#example-of-a-complete-dataset"><i class="fa fa-check"></i>Example of a complete dataset</a></li>
<li class="chapter" data-level="" data-path="manipulations-and-covariates.html"><a href="manipulations-and-covariates.html#aggregate-table-of-data"><i class="fa fa-check"></i>Aggregate table of data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html"><i class="fa fa-check"></i><b>4</b> Correlation Statistics and Plots</a>
<ul>
<li class="chapter" data-level="" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html#thinking-about-association"><i class="fa fa-check"></i>1. Thinking About Association</a></li>
<li class="chapter" data-level="" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html#what-is-already-known-about-these-varaibles"><i class="fa fa-check"></i>2. What is already known about these varaibles?</a></li>
<li class="chapter" data-level="" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html#power-analysis-what-sample-size-should-you-use"><i class="fa fa-check"></i>3. Power Analysis: what sample size should you use?</a></li>
<li class="chapter" data-level="" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html#a-picture-is-worth-100-words"><i class="fa fa-check"></i>4. A picture is worth 100 words…</a></li>
<li class="chapter" data-level="" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html#reflect-3"><i class="fa fa-check"></i>5. Reflect</a></li>
<li class="chapter" data-level="" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html#code-for-practical-4"><i class="fa fa-check"></i>Code for Practical #4</a>
<ul>
<li class="chapter" data-level="" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html#generate-data"><i class="fa fa-check"></i>Generate Data</a></li>
<li class="chapter" data-level="" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html#check-out-the-data"><i class="fa fa-check"></i>Check out the data</a></li>
<li class="chapter" data-level="" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html#check-the-correlation"><i class="fa fa-check"></i>Check the correlation</a></li>
<li class="chapter" data-level="" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html#code-to-generate-a-basic-scatterplot"><i class="fa fa-check"></i>Code to generate a basic scatterplot:</a></li>
<li class="chapter" data-level="" data-path="correlation-statistics-and-plots.html"><a href="correlation-statistics-and-plots.html#a-fancier-better-looking-scatterplot"><i class="fa fa-check"></i>A fancier, better looking scatterplot:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html"><i class="fa fa-check"></i><b>5</b> Connecting the IV and Covariate</a>
<ul>
<li class="chapter" data-level="" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#thinking-about-causality"><i class="fa fa-check"></i>1. Thinking About Causality</a></li>
<li class="chapter" data-level="" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#what-is-already-known"><i class="fa fa-check"></i>2. What is already known?</a></li>
<li class="chapter" data-level="" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#connect-the-theory-of-the-iv-dv-relationship-to-your-proposed-covariate."><i class="fa fa-check"></i>3. Connect the theory of the IV-DV relationship to your proposed covariate.</a></li>
<li class="chapter" data-level="" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#transform-the-continuous-covariate-to-a-categorical-variable"><i class="fa fa-check"></i>4. Transform the continuous covariate to a categorical variable</a></li>
<li class="chapter" data-level="" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#reflect-4"><i class="fa fa-check"></i>5. Reflect</a></li>
<li class="chapter" data-level="" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#code-for-practical-5"><i class="fa fa-check"></i>Code for Practical #5</a>
<ul>
<li class="chapter" data-level="" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#generate-data-1"><i class="fa fa-check"></i>Generate data</a></li>
<li class="chapter" data-level="" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#transform"><i class="fa fa-check"></i>Transform</a></li>
<li class="chapter" data-level="" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#make-a-bar-graph"><i class="fa fa-check"></i>Make a Bar Graph</a></li>
<li class="chapter" data-level="" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#analyze"><i class="fa fa-check"></i>Analyze</a></li>
<li class="chapter" data-level="" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#category-exmaple"><i class="fa fa-check"></i>3-category exmaple</a></li>
<li class="chapter" data-level="5.0.1" data-path="connecting-the-iv-and-covariate.html"><a href="connecting-the-iv-and-covariate.html#analyze-3-category-example"><i class="fa fa-check"></i><b>5.0.1</b> Analyze 3-category example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="capstone-project-a-simulated-research-paper.html"><a href="capstone-project-a-simulated-research-paper.html"><i class="fa fa-check"></i>Capstone Project: A Simulated Research Paper</a>
<ul>
<li class="chapter" data-level="" data-path="capstone-project-a-simulated-research-paper.html"><a href="capstone-project-a-simulated-research-paper.html#overview-1"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="capstone-project-a-simulated-research-paper.html"><a href="capstone-project-a-simulated-research-paper.html#introduction"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="capstone-project-a-simulated-research-paper.html"><a href="capstone-project-a-simulated-research-paper.html#methods"><i class="fa fa-check"></i>Methods</a></li>
<li class="chapter" data-level="" data-path="capstone-project-a-simulated-research-paper.html"><a href="capstone-project-a-simulated-research-paper.html#results"><i class="fa fa-check"></i>Results</a>
<ul>
<li class="chapter" data-level="" data-path="capstone-project-a-simulated-research-paper.html"><a href="capstone-project-a-simulated-research-paper.html#correlation-analysis"><i class="fa fa-check"></i>Correlation Analysis</a></li>
<li class="chapter" data-level="" data-path="capstone-project-a-simulated-research-paper.html"><a href="capstone-project-a-simulated-research-paper.html#one-way-analysis"><i class="fa fa-check"></i>One-Way Analysis</a></li>
<li class="chapter" data-level="" data-path="capstone-project-a-simulated-research-paper.html"><a href="capstone-project-a-simulated-research-paper.html#factorial-anova"><i class="fa fa-check"></i>Factorial ANOVA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="follow-up-pair-wise-comparisons.html"><a href="follow-up-pair-wise-comparisons.html"><i class="fa fa-check"></i>Follow up pair-wise comparisons</a>
<ul>
<li class="chapter" data-level="" data-path="follow-up-pair-wise-comparisons.html"><a href="follow-up-pair-wise-comparisons.html#linear-regression"><i class="fa fa-check"></i>Linear Regression</a></li>
<li class="chapter" data-level="" data-path="follow-up-pair-wise-comparisons.html"><a href="follow-up-pair-wise-comparisons.html#discussion"><i class="fa fa-check"></i>Discussion</a>
<ul>
<li class="chapter" data-level="" data-path="follow-up-pair-wise-comparisons.html"><a href="follow-up-pair-wise-comparisons.html#conclusions"><i class="fa fa-check"></i>Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="follow-up-pair-wise-comparisons.html"><a href="follow-up-pair-wise-comparisons.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Final Assignment</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="follow-up-pair-wise-comparisons" class="section level1 unnumbered hasAnchor">
<h1>Follow up pair-wise comparisons<a href="follow-up-pair-wise-comparisons.html#follow-up-pair-wise-comparisons" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="follow-up-pair-wise-comparisons.html#cb57-1" tabindex="-1"></a><span class="do">## Always two ways to follow up: #1:</span></span>
<span id="cb57-2"><a href="follow-up-pair-wise-comparisons.html#cb57-2" tabindex="-1"></a>long_data <span class="sc">%&gt;%</span></span>
<span id="cb57-3"><a href="follow-up-pair-wise-comparisons.html#cb57-3" tabindex="-1"></a>  <span class="fu">group_by</span>(age_cat) <span class="sc">%&gt;%</span></span>
<span id="cb57-4"><a href="follow-up-pair-wise-comparisons.html#cb57-4" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(value<span class="sc">~</span>Drug)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 10
##   age_cat  .y.   group1 group2    n1    n2       p p.signif   p.adj p.adj.signif
## * &lt;fct&gt;    &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;       
## 1 Under 65 value Contr… Drug      42    42 0.583   ns       0.583   ns          
## 2 Over 65  value Contr… Drug      42    44 0.00155 **       0.00155 **</code></pre>
<ul>
<li>There was no effect of the drug on IQ scores for people that were under 65 (p = 0.58).</li>
<li>There was a significant effect of the drug treatment on IQ scores for people that were over 65 (p = 0.0016).</li>
</ul>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="follow-up-pair-wise-comparisons.html#cb59-1" tabindex="-1"></a><span class="do">## Number 2: </span></span>
<span id="cb59-2"><a href="follow-up-pair-wise-comparisons.html#cb59-2" tabindex="-1"></a>long_data <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="follow-up-pair-wise-comparisons.html#cb59-3" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span></span>
<span id="cb59-4"><a href="follow-up-pair-wise-comparisons.html#cb59-4" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(value<span class="sc">~</span>Drug)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 10
##   variable .y.   group1 group2    n1    n2       p p.signif   p.adj p.adj.signif
## * &lt;fct&gt;    &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;       
## 1 IQ       value Contr… Drug      42    43 0.514   ns       0.514   ns          
## 2 Post_IQ  value Contr… Drug      42    43 0.00383 **       0.00383 **</code></pre>
<ul>
<li>There was no difference in IQ scores between the experimental groups before treatment (i.e., at the first IQ measurement p = 0.51)</li>
<li>At the second IQ test, participants in the “Drug” group had higher IQ scores than participants in the control group p = 0.0039.</li>
</ul>
<div id="linear-regression" class="section level3 unnumbered hasAnchor">
<h3>Linear Regression<a href="follow-up-pair-wise-comparisons.html#linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Compute, interpret, and graph the results of a multiple regression where the continuous covariate is entered as the predictor with the independent variable entered as the moderator. Interpret the linear relationships between the continuous covariate and the dependent variable at each level of your experimental treatment condition.</p>
<p>So far, we’ve worked with categorized versions of the covariate. But this was based on a construct that exists on a continuous scale in the real world (e.g., age, in my case). Now, run a linear regression of model the continuous relationship at the different levels of your independent variable.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="follow-up-pair-wise-comparisons.html#cb61-1" tabindex="-1"></a><span class="co"># Plot correlations between the continuous covariate and the DV for the two levels of your IV</span></span>
<span id="cb61-2"><a href="follow-up-pair-wise-comparisons.html#cb61-2" tabindex="-1"></a>A <span class="ot">&lt;-</span> final_data <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="follow-up-pair-wise-comparisons.html#cb61-3" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug) <span class="sc">%&gt;%</span></span>
<span id="cb61-4"><a href="follow-up-pair-wise-comparisons.html#cb61-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Age,<span class="at">y=</span>Post_IQ)) <span class="sc">+</span></span>
<span id="cb61-5"><a href="follow-up-pair-wise-comparisons.html#cb61-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">4</span>,<span class="at">alpha=</span><span class="fl">0.4</span>)<span class="sc">+</span></span>
<span id="cb61-6"><a href="follow-up-pair-wise-comparisons.html#cb61-6" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>)<span class="sc">+</span></span>
<span id="cb61-7"><a href="follow-up-pair-wise-comparisons.html#cb61-7" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Drug)<span class="sc">+</span></span>
<span id="cb61-8"><a href="follow-up-pair-wise-comparisons.html#cb61-8" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb61-9"><a href="follow-up-pair-wise-comparisons.html#cb61-9" tabindex="-1"></a></span>
<span id="cb61-10"><a href="follow-up-pair-wise-comparisons.html#cb61-10" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;graph_2.png&quot;</span>,A,<span class="at">height=</span><span class="fl">3.5</span>,<span class="at">width=</span><span class="dv">6</span>,<span class="at">dpi=</span><span class="dv">300</span>)</span>
<span id="cb61-11"><a href="follow-up-pair-wise-comparisons.html#cb61-11" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">&quot;graph_2.png&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-33"></span>
<img src="graph_2.png" alt="Side-by-side comparisons of continuous relationships at each level of the moderator." width="900" />
<p class="caption">
Figure 5.1: Side-by-side comparisons of continuous relationships at each level of the moderator.
</p>
</div>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="follow-up-pair-wise-comparisons.html#cb62-1" tabindex="-1"></a><span class="co"># Be creative and choose a visual depiction that works for you! </span></span>
<span id="cb62-2"><a href="follow-up-pair-wise-comparisons.html#cb62-2" tabindex="-1"></a>B <span class="ot">&lt;-</span> final_data <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href="follow-up-pair-wise-comparisons.html#cb62-3" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug) <span class="sc">%&gt;%</span></span>
<span id="cb62-4"><a href="follow-up-pair-wise-comparisons.html#cb62-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Age,<span class="at">y=</span>Post_IQ,<span class="at">colour=</span>Drug,<span class="at">fill=</span>Drug,<span class="at">shape=</span>Drug))<span class="sc">+</span></span>
<span id="cb62-5"><a href="follow-up-pair-wise-comparisons.html#cb62-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">4</span>,<span class="at">alpha=</span><span class="fl">0.4</span>)<span class="sc">+</span></span>
<span id="cb62-6"><a href="follow-up-pair-wise-comparisons.html#cb62-6" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>,<span class="at">alpha=</span><span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb62-7"><a href="follow-up-pair-wise-comparisons.html#cb62-7" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb62-8"><a href="follow-up-pair-wise-comparisons.html#cb62-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">legend.justification =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb62-9"><a href="follow-up-pair-wise-comparisons.html#cb62-9" tabindex="-1"></a></span>
<span id="cb62-10"><a href="follow-up-pair-wise-comparisons.html#cb62-10" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;graph_3.png&quot;</span>,B,<span class="at">height=</span><span class="dv">4</span>,<span class="at">width=</span><span class="dv">4</span>,<span class="at">dpi=</span><span class="dv">300</span>)</span>
<span id="cb62-11"><a href="follow-up-pair-wise-comparisons.html#cb62-11" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">&quot;graph_3.png&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-34"></span>
<img src="graph_3.png" alt="Overlapping lines show the different linear relationships for the two levels of the moderator variable." width="600" />
<p class="caption">
Figure 5.2: Overlapping lines show the different linear relationships for the two levels of the moderator variable.
</p>
</div>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="follow-up-pair-wise-comparisons.html#cb63-1" tabindex="-1"></a><span class="co"># Run a linear regression to measure whether the continuous relationship between the covariate and the DV differs at the two levels of your independent variable during the &quot;post-test&quot; measurement. </span></span>
<span id="cb63-2"><a href="follow-up-pair-wise-comparisons.html#cb63-2" tabindex="-1"></a>baseline_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> final_data, IQ <span class="sc">~</span> Age)</span>
<span id="cb63-3"><a href="follow-up-pair-wise-comparisons.html#cb63-3" tabindex="-1"></a><span class="fu">summary</span>(baseline_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = IQ ~ Age, data = final_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.851  -7.613  -0.847  10.302  33.607 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept) 123.8054     9.2884   13.33 &lt;0.0000000000000002 ***
## Age          -0.3600     0.1412   -2.55              0.0126 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.01 on 83 degrees of freedom
## Multiple R-squared:  0.07267,    Adjusted R-squared:  0.0615 
## F-statistic: 6.504 on 1 and 83 DF,  p-value: 0.0126</code></pre>
<ul>
<li>At the baseline IQ test, the model predicts that a 1-year increase in age is associated with a 0.32-point decrease in IQ score.</li>
</ul>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="follow-up-pair-wise-comparisons.html#cb65-1" tabindex="-1"></a><span class="co"># Run a linear regression to measure whether the continuous relationship between the covariate and the DV differs at the two levels of your independent variable during the &quot;post-test&quot; measurement. </span></span>
<span id="cb65-2"><a href="follow-up-pair-wise-comparisons.html#cb65-2" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> final_data, Post_IQ <span class="sc">~</span> Age <span class="sc">*</span> Drug)</span>
<span id="cb65-3"><a href="follow-up-pair-wise-comparisons.html#cb65-3" tabindex="-1"></a><span class="fu">summary</span>(a)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Post_IQ ~ Age * Drug, data = final_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -32.131  -6.764  -0.849   7.384  31.873 
## 
## Coefficients:
##              Estimate Std. Error t value          Pr(&gt;|t|)    
## (Intercept)  134.4990    15.7772   8.525 0.000000000000691 ***
## Age           -0.6202     0.2415  -2.568           0.01207 *  
## DrugDrug     -47.2863    20.5379  -2.302           0.02388 *  
## Age:DrugDrug   0.8744     0.3126   2.797           0.00643 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.13 on 81 degrees of freedom
## Multiple R-squared:  0.1798, Adjusted R-squared:  0.1494 
## F-statistic: 5.917 on 3 and 81 DF,  p-value: 0.001057</code></pre>
<ul>
<li>The model accounts for ~18% of the variability in IQ scores (F(3,81) = 5.92, p = 0.001).</li>
<li>The predicted IQ score for an individual that is 0 years old and did not receive the drug treatment is 134.499</li>
<li>A 1-year increase in age is associated with a 0.62-point decrease in IQ score among participants in the control group (t = 2.57, p = 0.012)</li>
<li>The relationship between age and IQ score was different at the two levels of drug treatment (t = 2.80, p = 0.006).</li>
</ul>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="follow-up-pair-wise-comparisons.html#cb67-1" tabindex="-1"></a><span class="co"># Check out the nature of the linear relationship between the continuous covariate and the DV at each level of your IV:</span></span>
<span id="cb67-2"><a href="follow-up-pair-wise-comparisons.html#cb67-2" tabindex="-1"></a><span class="do">## Control group first:</span></span>
<span id="cb67-3"><a href="follow-up-pair-wise-comparisons.html#cb67-3" tabindex="-1"></a>control_only <span class="ot">&lt;-</span> final_data[final_data<span class="sc">$</span>Drug <span class="sc">==</span> <span class="st">&quot;Control&quot;</span>, ]</span>
<span id="cb67-4"><a href="follow-up-pair-wise-comparisons.html#cb67-4" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> control_only, Post_IQ <span class="sc">~</span> Age)</span>
<span id="cb67-5"><a href="follow-up-pair-wise-comparisons.html#cb67-5" tabindex="-1"></a><span class="fu">summary</span>(c)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Post_IQ ~ Age, data = control_only)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -25.418  -6.565   1.707   6.598  31.873 
## 
## Coefficients:
##             Estimate Std. Error t value        Pr(&gt;|t|)    
## (Intercept) 134.4990    15.0797   8.919 0.0000000000469 ***
## Age          -0.6202     0.2308  -2.687          0.0105 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.5 on 40 degrees of freedom
## Multiple R-squared:  0.1529, Adjusted R-squared:  0.1317 
## F-statistic: 7.218 on 1 and 40 DF,  p-value: 0.01046</code></pre>
<ul>
<li>Variability in age accounts for a statistically significant 15% of the variability in IQ scores (R^2 = 0.153, p = 0.01).</li>
<li>Same result as in the multiple regression model above :)</li>
<li>Information about the relationship between X &amp; Y in the “reference” group.</li>
</ul>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="follow-up-pair-wise-comparisons.html#cb69-1" tabindex="-1"></a><span class="do">## Then the drug group: </span></span>
<span id="cb69-2"><a href="follow-up-pair-wise-comparisons.html#cb69-2" tabindex="-1"></a>Drug_only <span class="ot">&lt;-</span> final_data[final_data<span class="sc">$</span>Drug <span class="sc">==</span> <span class="st">&quot;Drug&quot;</span>, ]</span>
<span id="cb69-3"><a href="follow-up-pair-wise-comparisons.html#cb69-3" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> Drug_only, Post_IQ <span class="sc">~</span> Age)</span>
<span id="cb69-4"><a href="follow-up-pair-wise-comparisons.html#cb69-4" tabindex="-1"></a><span class="fu">summary</span>(d)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Post_IQ ~ Age, data = Drug_only)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -32.131  -6.412  -1.443   9.133  31.348 
## 
## Coefficients:
##             Estimate Std. Error t value    Pr(&gt;|t|)    
## (Intercept)  87.2127    13.6920    6.37 0.000000129 ***
## Age           0.2542     0.2066    1.23       0.226    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.71 on 41 degrees of freedom
## Multiple R-squared:  0.0356, Adjusted R-squared:  0.01207 
## F-statistic: 1.513 on 1 and 41 DF,  p-value: 0.2256</code></pre>
<ul>
<li>Variability in age only accounts for 3% of variability in IQ scores, which is not statistically significant (p = 0.226).</li>
<li>Among drug-treated participants, age is no longer a significant predictor of IQ (p = 0.226).</li>
<li>Moreover, the (non-statistically-significant) estimate is positive for the drug group (b = 0.25).</li>
</ul>
</div>
<div id="discussion" class="section level2 unnumbered hasAnchor">
<h2>Discussion<a href="follow-up-pair-wise-comparisons.html#discussion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Unpack / explain the results from your current simulated experiment in the context of the literature that you cited in your introduction. What would these findings indicate? Why would they be important? In what ways would this finding be meaningful? What would these results indicate about the constructs that you are aiming to capture?</p>
<p>Please also explain what grouping the covariate into categories (and running factorial ANOVA) versus using linear regression on the continuous covariate add to your understanding of the measured variables.</p>
<p>The discussion should be between 1000 - 2000 words. Focus on <strong><em>quality</em></strong> rather than quantity. Subheadings are often useful in the discussion section. Use subheadings in such a way that they enhance your narrative. Make sure that you are <strong><em>discussing</em></strong> the findings (i.e., don’t just re-state the results).</p>
<p>Here, you should also reflect on the strengths and weaknesses of your current approach. Connect your theoretical study to real-world scenarios. Should this research be carried out in real life? Why or why not? Are there other, more logical or feasible versions of this experiment that should or could be conducted? Any thoughts about experimental design for future researchers?</p>
<div id="conclusions" class="section level3 unnumbered hasAnchor">
<h3>Conclusions<a href="follow-up-pair-wise-comparisons.html#conclusions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Drug treatment does not improve IQ on its own, but it seems to reverse age-related cognitive declines on the IQ test.</li>
</ul>
</div>
</div>
<div id="references" class="section level2 unnumbered hasAnchor">
<h2>References<a href="follow-up-pair-wise-comparisons.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>List your references in alphabetical order, using internal APA format (no hanging indents).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="capstone-project-a-simulated-research-paper.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/06-Final_Project.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
